### ISSUE TITLE
Plugin not Working in NobeBB version 0.6.1 

### ISSUE THREAD

**Issue by surajdalvi** [julianlam/nodebb-plugin-write-api#17]
I had installed **nodebb-plugin-write-api** in NodeBB **0.7.0-dev** version and it worked on it but when i try to use the same plugin in **0.6.1** version it does not work . It gives me following error:

 - error: [plugins] Error executing 'static:app.load' in plugin
'nodebb-plugin-write-api'
 - error:  Error: Route.post() requires callback functions but g
ot a [object Undefined]
    at Route.<anonymous> (D:\nodebb\node_modules\nodebb-plugin-write
-api\node_modules\express\lib\router\route.js:170:15)
    at Array.forEach (native)
    at Route.(anonymous function) [as post] (D:\nodebb\node_modules\
nodebb-plugin-write-api\node_modules\express\lib\router\route.js:166:15)
    at Function.proto.(anonymous function) (D:\nodebb\node_modules\n
odebb-plugin-write-api\node_modules\express\lib\router\index.js:498:19)
    at module.exports (D:\nodebb\node_modules\nodebb-plugin-write-ap
i\routes\v1\groups.js:22:6)
    at module.exports (D:\nodebb\node_modules\nodebb-plugin-write-ap
i\routes\v1\index.js:10:40)
    at module.exports (D:\nodebb\node_modules\nodebb-plugin-write-ap
i\routes\index.js:7:26)
    at Object.API.init [as method] (D:\nodebb\node_modules\nodebb-pl
ugin-write-api\index.js:14:34)
    at D:\nodebb\src\plugins\hooks.js:127:14
    at D:\nodebb\node_modules\async\lib\async.js:125:13

Also I wanted to know about version 0.7 when can I expect it to be released as a stable version.

please help me into it?

**Comment by julianlam** [comment]
Hi Suraj, 

This plugin will not be backported to v0.6.x, it is only compatible with 0.7.0.

**Comment by surajdalvi** [comment]
HI

I wanted to know about version 0.7.0 when can I expect it to be released as a stable version? currently version 0.7.0 is dev  but I want stable version of it

**Comment by surajdalvi** [comment]
HI,

Thanks for your help but I wanted to know about **v0.7.0** when can I expect it to be released as a stable version?  

currently version 0.7.0 is in dev but I want stable version of it.

**Comment by surajdalvi** [comment]
HI,
Thanks for your reply.
I am changing Nodebb database from redis to mongodb. For that I am using this plugin to migrate redis data to mongodb, but its not supporting in **v0.6.x**.
Could you please help me here or when do we expect  stable release of **v0.7.0** ?

**Comment by julianlam** [comment]
v0.7.0 is approaching launch, so it should be safe to use it. 

Do not post the same query multiple times on different issues please.
