### ISSUE TITLE
Remote auth

### ISSUE THREAD

**Issue by AlvaroFranco** [julianlam/nodebb-plugin-write-api#3]
It would be great to get the user token with a POST request, passing the user and the md5 pass as POST fields, returning the user token in order to perform requests.

**Comment by julianlam** [comment]
Hey there, thanks for the comment!

I'd like to eventually bring OAuth (possibly OAuth2) endpoints into the mix, although simple token generation is sufficient for development purposes.

Have you tried generating the token in the ACP?

**Comment by AlvaroFranco** [comment]
So, I suppose this is only for development purpose? It would be great to auth any user with its email/username and pass. Is this a WIP by any chance?

**Comment by julianlam** [comment]
This plugin is designed to eventually be production ready.

The token generation form in the ACP is fine, although for best security we
should implement OAuth.

**Comment by AlvaroFranco** [comment]
I mean, if I generate a token on the ACP, I have 1 token per forum, instead of 1 token per user, right? My point is that this plugin should be meant to get the user token from his user and password.

**Comment by julianlam** [comment]
The ACP interface should allow you to create as many keys as you want
(since its only accessible by admins). You can specify the uid the token is
associated with.

Later on, we'll add in proper token generation for all users.
