### ISSUE TITLE
How to update and delete resources?

### ISSUE THREAD

**Issue by atomoc** [julianlam/nodebb-plugin-write-api#6]
The README.md is written how to create: `curl -H "Authorization: Bearer {YOUR_TOKEN}" --data "title={TITLE}&content={CONTENT}&cid={CID}" http://localhost:4567/api/v1/topics`
But there is no description of how to update and delete resources. Please, write about that.

**Comment by julianlam** [comment]
Like this is not coded into the write-api now. You can `PUT` a topic, however.
